# Generated by Django 4.2.3 on 2023-07-18 16:31

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=20)),
                ('encargado', models.CharField(max_length=20)),
                ('celular', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('goles_local', models.PositiveIntegerField()),
                ('goles_visitante', models.PositiveIntegerField()),
                ('puntos_local', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('puntos_visitante', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('fecha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneo.fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_equipos', models.IntegerField()),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('identificacion', models.CharField(max_length=25)),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneo.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Partido_Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_equipo_local', to='Torneo.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_equipo_visitante', to='Torneo.equipo')),
                ('partido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneo.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Judador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=25)),
                ('apellidos', models.CharField(max_length=25)),
                ('identificacion', models.CharField(max_length=25)),
                ('nacimiento', models.DateField()),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneo.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='fecha',
            name='torneo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneo.torneo'),
        ),
    ]
